#!/usr/bin/env python3.9

VIZ_CHART_INTERVAL = "2H"
VIZ_CYCLE_LOOKBACK = 86400
VIZ_CHART_SMOOTH = 1
VIZ_CHART_FOREGROUND = "white"
VIZ_CHART_BACKGROUND = "#1380af"
VIZ_CHART_FOREGROUND_BAD = "white"
VIZ_CHART_BACKGROUND_BAD = "#9b2226"
VIZ_CHART_FOREGROUND_NONE = "white"
VIZ_CHART_BACKGROUND_NONE = "#00000000"
VIZ_CHART_WIDTH = 1024
VIZ_CHART_HEIGHT = 512
